"use client"

import { Card, CardContent } from "@/components/ui/card"
import Image from "next/image"

interface ContentDisplayProps {
  type: string
  content: string
  modelName: string
}

export function ContentDisplay({ type, content, modelName }: ContentDisplayProps) {
  const renderContent = () => {
    switch (type) {
      case "text":
        return <div className="p-4 bg-muted rounded-md whitespace-pre-wrap">{content}</div>
      case "image":
        return (
          <div className="flex justify-center">
            <Image
              src={content || "/placeholder.svg"}
              alt={`Generated by ${modelName}`}
              width={300}
              height={300}
              className="rounded-md"
            />
          </div>
        )
      case "video":
        return (
          <div className="p-4 bg-muted rounded-md text-center">
            <div className="w-full h-48 bg-background flex items-center justify-center border rounded-md">
              <p className="text-muted-foreground">Video Player Placeholder</p>
            </div>
            <p className="mt-2">{content}</p>
          </div>
        )
      case "audio":
        return (
          <div className="p-4 bg-muted rounded-md text-center">
            <div className="w-full h-24 bg-background flex items-center justify-center border rounded-md">
              <p className="text-muted-foreground">Audio Player Placeholder</p>
            </div>
            <p className="mt-2">{content}</p>
          </div>
        )
      case "3d":
        return (
          <div className="p-4 bg-muted rounded-md text-center">
            <div className="w-full h-48 bg-background flex items-center justify-center border rounded-md">
              <p className="text-muted-foreground">3D Viewer Placeholder</p>
            </div>
            <p className="mt-2">{content}</p>
          </div>
        )
      default:
        return <p>{content}</p>
    }
  }

  return (
    <Card>
      <CardContent className="pt-6">{renderContent()}</CardContent>
    </Card>
  )
}
